// web-ui-vue/src/components/Board.vue
<template>
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">{{ board.title }}</h3>
            </div>
            <div class="input-group">
                <input
                    class="form-control"
                    placeholder="find task"
                    v-model="filter"
                    v-on:input="filterTasks"
                />
            </div>
            <div class="panel-body">
                <div
                    class="list-group-item"
                    v-bind:key="task.id"
                    v-for="task in tasks"
                >
                    {{ task.task }}
                </div>
            </div>
            <div class="input-group">
                <input class="form-control" placeholder="add new task" />
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary">Add</button>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: "Board",
    props: ["board"],
    data() {
        return {
            tasks: [],
            filter: "",
        };
    },
    created() {
        fetch(`/api/board/${this.board.id}/tasks`)
            .then((res) => res.json())
            .then((tasks) => {
                console.log(tasks);
                this.tasks = tasks;
            });
    },
    methods: {
        filterTasks() {
            fetch(`/api/boards/${this.board.id}/tasks/search`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({
                    text: this.filter,
                }),
            })
                .then((res) => res.json())
                .then((res) => (this.tasks = res));
        },
    },
};
</script>

// web-ui-react/src/components/Board.jsx
import React, { useEffect, useState } from 'react'

export const Board = ({ board }) => {

  const [tasks, setTasks] = useState();
  const [inputNewTask, setInputNewTask] = useState();
  const [filter, setFilter] = useState('');

  useEffect(() => {
    if (board.id !== undefined) {
      fetch(`/api/board/${board.id}/tasks`)
        .then((res) => res.json())
        .then((tasks) => {
          setTasks(tasks);
        });
    }
  }, [board.id]);

  useEffect(() => {
    if (filter) {
      fetch(`/api/boards/${board.id}/tasks/search`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          text: filter,
        }),
      })
        .then((res) => res.json())
        .then((res) => setTasks(res));
    }
  }, [filter])

  const onClick = () => {
    console.log('click', inputNewTask);

    fetch("/api/tasks", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        task: { task: inputNewTask, boardId: board.id },
      }),
    })
      .then((res) => res.json())
      .then((res) => setTasks(res));
  }

  return (
    <div>
      <div className="col-md-4">
        <div className="panel panel-primary">
          <div className="panel-heading">
            <h3 className="panel-title">{board.title}</h3>
          </div>
          <div className="input-group">
            <input
              className="form-control"
              placeholder="find task"
              onChange={(e) => setFilter(e.target.value)}
            />
          </div>
          <div className="panel-body">
            {!tasks && <div>Loading</div>}
            {tasks?.map(({ task, id }) => (
              <div
                key={id}
                className="list-group-item"
              >
                {task}
              </div>
            ))}
            {tasks && tasks.length === 0 && <div>Nothing to show</div>}
          </div>
          <div className="input-group">
            <input className="form-control" placeholder="add new task" onChange={(e) => setInputNewTask(e.target.value)} />
            <div className="input-group-append">
              <button className="btn btn-outline-secondary" onClick={onClick}>Add</button>
            </div>
          </div>
        </div>
      </div>
    </div >
  )
}
