// web-ui-angular/src/app/board/board.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { BoardService } from '../services/board.service';

@Component({
  selector: 'app-board',
  templateUrl: './board.component.html',
  styleUrls: ['./board.component.scss'],
})
export class BoardComponent implements OnInit {
  @Input() board;
  tasks;
  filter;

  constructor(private boardService: BoardService) {}

  ngOnInit(): void {
    this.boardService.getBoardTasks(this.board.id).subscribe((tasks) => {
      console.log('tasks', tasks);
      this.tasks = tasks;
    });
  }

  onFilterChange(): void {
    this.boardService
      .filterTasks(this.board.id, this.filter)
      .subscribe((tasks) => {
        this.tasks = tasks;
      });
  }
}

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">{{ board.title }}</h3>
  </div>
  <div class="input-group">
    <input
      class="form-control"
      placeholder="find task"
      [(ngModel)]="filter"
      (input)="onFilterChange()"
    />
  </div>
  <div class="panel-body" *ngFor="let task of tasks">
    <div class="list-group-item">{{ task.task }}</div>
  </div>
  <div class="input-group">
    <input class="form-control" placeholder="add new task" />
    <div class="input-group-append">
      <button class="btn btn-outline-secondary">Add</button>
    </div>
  </div>
</div>

// web-ui-react/src/components/Board.jsx
import React, { useEffect, useState } from 'react'

export const Board = ({ board }) => {


  const [tasks, setTasks] = useState();
  const [filter, setFilter] = useState();

  useEffect(() => {
    if (board.id !== undefined) {
      fetch(`/api/board/${board.id}/tasks`)
        .then((res) => res.json())
        .then((tasks) => {
          setTasks(tasks);
        });
    }
  }, [board.id]);

  return (
    <div>
      <div className="col-md-4">
        <div className="panel panel-primary">
          <div className="panel-heading">
            <h3 className="panel-title">{board.title}</h3>
          </div>
          <div className="input-group">
            <input
              className="form-control"
              placeholder="find task"
              value={filter}
              onChange={(e) => setFilter(e.target.value)}
            />
          </div>
          <div className="panel-body">
            {tasks?.map(({ task, id }) => (
              <div
                key={id}
                className="list-group-item"
              >
                {task}
              </div>
            ))}

          </div>
          <div className="input-group">
            <input className="form-control" placeholder="add new task" />
            <div className="input-group-append">
              <button className="btn btn-outline-secondary">Add</button>
            </div>
          </div>
        </div>
      </div>
    </div >
  )
}
