// web-ui-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { BoardService } from './services/board.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  title = 'My Kanban';
  boards;

  constructor(private boardService: BoardService) {}

  ngOnInit(): void {
    this.boardService.getBoards().subscribe((boards) => {
      this.boards = boards;
      console.log('boards', boards);
    });
  }
}

<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-brand">{{ title }}</div>
  </div>
</div>
<div class="container">
  <div class="row">
    <app-board
      class="col-sm-4"
      *ngFor="let board of boards"
      [board]="board"
    ></app-board>
  </div>
</div>

// web-ui-react/src/App.js
import logo from "./logo.svg";
import "./App.css";
import { useEffect, useState } from "react";
import { Board } from "./components/Board";

const TITLE = "Kanban";

function App() {
    const [boards, setBoards] = useState();

    useEffect(() => {
        fetch("/api/boards")
            .then((res) => res.json())
            .then((boards) => {
                console.log("boards", boards);
                setBoards(boards);
            });
    }, []);

    return (
        <div>
            <div className="navbar navbar-default">
                <div className="container">
                    <div className="navbar-brand">{TITLE}</div>
                </div>
            </div>
            <div className="container">
                <div className="row">
                    {boards?.map((board) => (
                        <Board key={board.id} board={board} />
                    ))}
                </div>
            </div>
        </div>
    );
}

export default App;
